from faster_whisper import WhisperModel

def generate_subtitles(audio_path: str):
    """
    Transcribes the audio file and extracts word-level timestamps using faster-whisper.
    Returns a list of dictionaries, each containing 'word', 'start', and 'end' time.
    """
    print(f"Loading whisper model for subtitles...")
    # Using 'base' or 'small' model for speed. 'base' is usually fine for clear AI voices.
    model = WhisperModel("base", device="cpu", compute_type="int8")
    
    print(f"Transcribing audio: {audio_path}")
    # word_timestamps=True is the key to getting exact timings for each word
    segments, info = model.transcribe(audio_path, word_timestamps=True)
    
    subtitles = []
    for segment in segments:
        for word in segment.words:
            subtitles.append({
                "word": word.word.strip(),
                "start": word.start,
                "end": word.end
            })
            
    print(f"Generated {len(subtitles)} subtitle parts.")
    return subtitles

if __name__ == "__main__":
    # Test subtitle agent
    # Make sure you have a test_audio.mp3 generated by voice_agent.py first
    try:
        subs = generate_subtitles("test_audio.mp3")
        for s in subs[:5]:
            print(s)
    except Exception as e:
        print(f"Error test: {e}")
